### ISSUE TITLE
加载世界时崩溃，提示IllegalArgumentException: null in argument

### ISSUE THREAD

**Issue by lanStar2003** [Nxer/Twist-Space-Technology-Mod#167]
GTNH2.5.1 安装tst0.4.3+版本后，游戏正常进入，进入世界会直接崩溃
之前版本没有问题
[23:46:06] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[23:46:06] [Server thread/ERROR] [FML/]: Caught exception from TwistSpaceTechnology
java.lang.IllegalArgumentException: null in argument
	at gregtech.api.util.GT_RecipeBuilder.handleNullRecipeComponents(GT_RecipeBuilder.java:173) ~[GT_RecipeBuilder.class:?]
	at gregtech.api.util.GT_RecipeBuilder.itemInputs(GT_RecipeBuilder.java:230) ~[GT_RecipeBuilder.class:?]
	at com.Nxer.TwistSpaceTechnology.recipe.machineRecipe.AssemblyLineWithoutResearchRecipePool.loadRecipes(AssemblyLineWithoutResearchRecipePool.java:98) ~[AssemblyLineWithoutResearchRecipePool.class:?]
	at com.Nxer.TwistSpaceTechnology.loader.RecipeLoader.loadRecipes(RecipeLoader.java:56) ~[RecipeLoader.class:?]
	at com.Nxer.TwistSpaceTechnology.TwistSpaceTechnology.completeInit(TwistSpaceTechnology.java:120) ~[TwistSpaceTechnology.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:745) ~[Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3099) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[GTNH251.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[Wrapper.class:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[Wrapper.class:?]

**Comment by lanStar2003** [comment]
[fml-client-latest.txt](https://github.com/Nxer/Twist-Space-Technology-Mod/files/13766683/fml-client-latest.txt)

**Comment by Nxer** [comment]
升级版本

**Comment by lanStar2003** [comment]
0.4.5版本依旧会出现这个问题

**Comment by Nxer** [comment]
是不是BoxPlusPlus升级1.54了，NVIDIA晶圆厂配方有点问题，会导致这个空指针。我下来会进行手动排空

**Comment by lanStar2003** [comment]
确实是他的问题，删除boxplusplus后解决

**Comment by Nxer** [comment]
boxpp降1.52就好了，或者等TST下个版本

**Comment by Nxer** [comment]
修了 #168
