### ISSUE TITLE
Mod 不支持最新版 MuTE 系统

### ISSUE THREAD

**Issue by foxwhite25** [Nxer/Twist-Space-Technology-Mod#188]
在最新版的 GT main branch 合并了一个重构多方块系统，这些版本仍然没在 GTNH 2.6.0-nightly 里面但是可能会在一段时间之后加入 GTNH。https://github.com/GTNewHorizons/GT5-Unofficial/commit/02bedd5c0a96a654c6692edd1b7f2765fd9c46b4

这只是最小的报错，但是可能会有更多不兼容需要修一下
```
java.lang.NoSuchMethodError: 'gregtech.api.logic.ProcessingLogic com.Nxer.TwistSpaceTechnology.system.OreProcess.machines.TST_OreProcessingFactory$1.setMaxParallel(int)'
    at com.Nxer.TwistSpaceTechnology.system.OreProcess.machines.TST_OreProcessingFactory.createProcessingLogic(TST_OreProcessingFactory.java:350)
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.<init>(GT_MetaTileEntity_MultiBlockBase.java:168)
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_TooltipMultiBlockBase.<init>(GT_MetaTileEntity_TooltipMultiBlockBase.java:25)
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_EnhancedMultiBlockBase.<init>(GT_MetaTileEntity_EnhancedMultiBlockBase.java:45)
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase.<init>(GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java:39)
    at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase.<init>(GTCM_MultiMachineBase.java:41)
    at com.Nxer.TwistSpaceTechnology.system.OreProcess.machines.TST_OreProcessingFactory.<init>(TST_OreProcessingFactory.java:89)
    at com.Nxer.TwistSpaceTechnology.system.OreProcess.machines.TST_OreProcessingFactory.newMetaEntity(TST_OreProcessingFactory.java:94)
    at gregtech.api.metatileentity.CommonMetaTileEntity.createNewMetatileEntity(CommonMetaTileEntity.java:41)
    at gregtech.api.metatileentity.BaseMetaTileEntity.setInitialValuesAsNBT(BaseMetaTileEntity.java:172)
    at gregtech.common.blocks.GT_Item_Machines.placeBlockAt(GT_Item_Machines.java:301)
    at net.minecraft.item.ItemBlock.onItemUse(ItemBlock.java:103)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
    at net.minecraft.item.ItemStack.tryPlaceItemIntoWorld(ItemStack.java:128)
    at net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(SourceFile:9)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Nxer** [comment]
OK

**Comment by Nxer** [comment]
maybe fixed #189

**Comment by Nxer** [comment]
maybe fixed #189
