### ISSUE TITLE
2.5.0 can't see multi structures

### ISSUE THREAD

**Issue by AimaGod** [Nxer/Twist-Space-Technology-Mod#334]
[19:47:13] [ForkJoinPool-1-worker-11/ERROR] [NotEnoughItems]: Error while looking up crafting recipe
[19:47:13] [ForkJoinPool-1-worker-11/ERROR] [NotEnoughItems]: outputId: item
[19:47:13] [ForkJoinPool-1-worker-11/ERROR] [NotEnoughItems]: results: [1xgt.blockmachines@19022]
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoSuchMethodError: com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase$1.setMaxParallelSupplier(Ljava/util/function/Supplier;)Lgregtech/api/logic/AbstractProcessingLogic;
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase.createProcessingLogic(GTCM_MultiMachineBase.java:86)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.<init>(GT_MetaTileEntity_MultiBlockBase.java:165)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_TooltipMultiBlockBase.<init>(GT_MetaTileEntity_TooltipMultiBlockBase.java:25)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_EnhancedMultiBlockBase.<init>(GT_MetaTileEntity_EnhancedMultiBlockBase.java:45)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase.<init>(GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java:39)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase.<init>(GTCM_MultiMachineBase.java:48)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.Nxer.TwistSpaceTechnology.common.machine.GT_TileEntity_MegaBrickedBlastFurnace.<init>(GT_TileEntity_MegaBrickedBlastFurnace.java:561)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.Nxer.TwistSpaceTechnology.common.machine.GT_TileEntity_MegaBrickedBlastFurnace.newMetaEntity(GT_TileEntity_MegaBrickedBlastFurnace.java:581)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.CommonMetaTileEntity.createNewMetatileEntity(CommonMetaTileEntity.java:41)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.setInitialValuesAsNBT(BaseMetaTileEntity.java:172)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gregtech.common.blocks.GT_Item_Machines.placeBlockAt(GT_Item_Machines.java:300)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blockrenderer6343.integration.gregtech.GT_GUI_MultiblocksHandler.placeMultiblock(GT_GUI_MultiblocksHandler.java:187)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blockrenderer6343.common.GUI_MultiblocksHandler.initializeSceneRenderer(GUI_MultiblocksHandler.java:280)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blockrenderer6343.integration.gregtech.GT_GUI_MultiblocksHandler.loadNewMultiblock(GT_GUI_MultiblocksHandler.java:104)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blockrenderer6343.common.GUI_MultiblocksHandler.loadMultiblock(GUI_MultiblocksHandler.java:102)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.tryLoadMultiblocks(GT_NEI_MultiblocksHandler.java:147)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.loadCraftingRecipes(GT_NEI_MultiblocksHandler.java:102)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:418)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blockrenderer6343.integration.nei.GT_NEI_MultiblocksHandler.loadCraftingRecipes(GT_NEI_MultiblocksHandler.java:97)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:556)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.recipe.GuiCraftingRecipe.lambda$getCraftingHandlers$0(GuiCraftingRecipe.java:69)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.nei.recipe.RecipeHandlerQuery.lambda$null$2(RecipeHandlerQuery.java:77)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[19:47:13] [ForkJoinPool-1-worker-11/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

got this from prism

**Comment by Nxer** [comment]
wtf, you're using TST nightly version for GTNH 2.5.1 ? The game should just crash but you just got a structure preview error.
