### ISSUE TITLE
希望重制一下深度化学扭曲仪（合成老是出问题）

### ISSUE THREAD

**Issue by QianWJ411** [Nxer/Twist-Space-Technology-Mod#417]
版本是0.4.29-2.5.1fitted
首先是化反模式下，深度化学扭曲仪读取到总成里面如果有两个配方，会直接崩溃关机。服务器后台没有爆错反馈（总成是tst自带的）如果不清空，拆下控制器放下成型还是会提示崩溃关机。
然后就是扭的配方了。深度化学扭流体比较大，很难直接使用总成，采取了发配子网，存储输入输入总线和几个输入仓。如果别的输入总线和输入仓也存其他的配方了（不是同一个电路板）。扭就不工作了。（显示找不到合成表，无崩溃关机）哪怕是把其中一个配方清空也不工作。只能清空一个配方，然后拆掉控制器重放，估计是和崩溃关机一样

**Comment by Nxer** [comment]
服务器后台没有直接打印错误信息依旧会存到日志文件里

**Comment by DrFeelgood123154** [comment]
2.6.0 上崩溃，任何机器都会出现这种情况

java.lang.NoSuchMethodError: 'gregtech.api.logic.ProcessingLogic com.Nxer.TwistSpaceTechnology.common.machine.GT_TileEntity_IntensifyChemicalDistorter$1.enablePerfectOverclock()'
	at RFB-Launch//com.Nxer.TwistSpaceTechnology.common.machine.GT_TileEntity_IntensifyChemicalDistorter.createProcessingLogic(GT_TileEntity_IntensifyChemicalDistorter.java:120)
	at RFB-Launch//gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.<init>(GT_MetaTileEntity_MultiBlockBase.java:175)
	at RFB-Launch//gregtech.api.metatileentity.implementations.GT_MetaTileEntity_TooltipMultiBlockBase.<init>(GT_MetaTileEntity_TooltipMultiBlockBase.java:25)
	at RFB-Launch//gregtech.api.metatileentity.implementations.GT_MetaTileEntity_EnhancedMultiBlockBase.<init>(GT_MetaTileEntity_EnhancedMultiBlockBase.java:46)
	at RFB-Launch//gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase.<init>(GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java:43)
	at RFB-Launch//com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase.<init>(GTCM_MultiMachineBase.java:49)
	at RFB-Launch//com.Nxer.TwistSpaceTechnology.common.machine.GT_TileEntity_IntensifyChemicalDistorter.<init>(GT_TileEntity_IntensifyChemicalDistorter.java:78)
	at RFB-Launch//com.Nxer.TwistSpaceTechnology.common.machine.GT_TileEntity_IntensifyChemicalDistorter.newMetaEntity(GT_TileEntity_IntensifyChemicalDistorter.java:385)
	at RFB-Launch//gregtech.api.metatileentity.CommonMetaTileEntity.createNewMetatileEntity(CommonMetaTileEntity.java:41)
	at RFB-Launch//gregtech.api.metatileentity.CommonMetaTileEntity.loadMetaTileNBT(CommonMetaTileEntity.java:81)
	at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.setInitialValuesAsNBT(BaseMetaTileEntity.java:210)
	at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145839_a(BaseMetaTileEntity.java:170)
	at RFB-Launch//net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116)
	at RFB-Launch//net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496)
	at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:235)
	at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by QianWJ411** [comment]
请问有没有关键词，在一堆之前的压缩包里很难找

**Comment by DrFeelgood123154** [comment]
我认为这个问题现在已经解决了，我们只需要等待新版本的发布。我们使用的 mod 版本为 2.5.1，最新版本为 2.6.0

**Comment by Nxer** [comment]
> 我认为这个问题现在已经解决了，我们只需要等待新版本的发布。我们使用的 mod 版本为 2.5.1，最新版本为 2.6.0
> 

有没有可能，TST有两个版本，其中一个版本是专门适配2.5.1的，另一个才是跟进最新GTNH的版本。你用2.5.1专门适配版的TST装在GTNH2.6.0不崩溃才是不正常

**Comment by Nxer** [comment]
> 请问有没有关键词，在一堆之前的压缩包里很难找

./log/latest.log  或者其他什么，你可以直接把 log文件夹打包发我一下

**Comment by DrFeelgood123154** [comment]
> > I think this issue is resolved now and we just have to wait for the new version to be released. The mod version we are using is 2.5.1, and the latest version is 2.6.0
> 
> Is it possible that TST has two versions, one of which is specially adapted to 2.5.1, and the other is a version that follows the latest GTNH. It is abnormal if you use the 2.5.1 specially adapted version of TST to install it in GTNH 2.6.0 and it does not crash.

好吧，它已经为我解决了，可能会有更多的人犯和我一样的错误，票务O​​P你可能想检查一下你是否使用了正确的版本。
