### ISSUE TITLE
0.4.30-2.5.1fitted-test缺少一个依赖

### ISSUE THREAD

**Issue by bingyouD** [Nxer/Twist-Space-Technology-Mod#441]
![Uploading Cache_787b154885753430.png…]()

**Comment by bingyouD** [comment]
![Uploading _0629029cd161561efda75b3167fcf537_-1606366252_Cache_787b154885753430.png…]()
[22:03:51] [Client thread/ERROR]: The following problems were captured during this phase
[22:03:51] [Client thread/ERROR]: Caught exception from TwistSpaceTechnology
java.lang.NoClassDefFoundError: com/gtnewhorizons/modularui/api/NumberFormatMUI
	at com.Nxer.TwistSpaceTechnology.common.machine.GTCM_LightningSpire.<clinit>(GTCM_LightningSpire.java:474) ~[GTCM_LightningSpire.class:?]
	at com.Nxer.TwistSpaceTechnology.loader.MachineLoader.loadMachines(MachineLoader.java:579) ~[MachineLoader.class:?]
	at com.Nxer.TwistSpaceTechnology.TwistSpaceTechnology.init(TwistSpaceTechnology.java:108) ~[TwistSpaceTechnology.class:?]
