### ISSUE TITLE
精密高能光量子掌控者处理兰波顿水晶刻蚀配方时出错

### ISSUE THREAD

**Issue by ZivilynNks** [Nxer/Twist-Space-Technology-Mod#48]
java.lang.NullPointerException
	at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.processingLogics.GTCM_ParallelHelper.determineParallel(GTCM_ParallelHelper.java:524)
	at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.processingLogics.GTCM_ParallelHelper.build(GTCM_ParallelHelper.java:308)
	at gregtech.api.recipe.check.RecipeValidator.checkRecipe(RecipeValidator.java:53)
	at gregtech.api.recipe.check.RecipeValidator.test(RecipeValidator.java:36)
	at gregtech.api.recipe.check.RecipeValidator.test(RecipeValidator.java:14)
	at gregtech.api.util.GT_Recipe$GT_Recipe_Map.findRecipeWithResult(GT_Recipe.java:4081)
	at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.processingLogics.GTCM_ProcessingLogic.findRecipe(GTCM_ProcessingLogic.java:404)
	at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.processingLogics.GTCM_ProcessingLogic.process(GTCM_ProcessingLogic.java:292)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.doCheckRecipe(GT_MetaTileEntity_MultiBlockBase.java:801)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkProcessing(GT_MetaTileEntity_MultiBlockBase.java:712)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.checkRecipe(GT_MetaTileEntity_MultiBlockBase.java:480)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.runMachine(GT_MetaTileEntity_MultiBlockBase.java:572)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:400)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:535)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.u.a(F:289)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

红字崩溃导致机器关机

**Comment by ZivilynNks** [comment]
版本： gregtech-5.09.44.03 TwistSpaceTechnology-0.22

**Comment by Nxer** [comment]
暂时不兼容矿辞配方，等GTNH-2.4.2发布即可修复
