### ISSUE TITLE
[bug]更新tst0.6.2与GS1.1.105后无法启动服务器

### ISSUE THREAD

**Issue by PinkYuDeer** [Nxer/Twist-Space-Technology-Mod#705]
- 完整日志：[fml-server-latest.log](https://github.com/user-attachments/files/18272941/fml-server-latest.log)

<details> <summary><font size="4" color="orange">HighLight</font></summary> <pre><code class="language-cpp">
[16:00:04] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[16:00:04] [Server thread/ERROR] [FML/]: Caught exception from TwistSpaceTechnology
java.lang.NoSuchFieldError: Class galaxyspace.core.register.GSItems does not have member field 'net.minecraft.item.Item DysonSwarmItems'
	at Launch//com.Nxer.TwistSpaceTechnology.recipe.machineRecipe.GTCMMachineRecipePool.loadRecipes(GTCMMachineRecipePool.java:2287) ~[GTCMMachineRecipePool.class:?]
	at Launch//com.Nxer.TwistSpaceTechnology.loader.RecipeLoader.loadRecipes(RecipeLoader.java:77) ~[RecipeLoader.class:?]
	at Launch//com.Nxer.TwistSpaceTechnology.TwistSpaceTechnology.completeInit(TwistSpaceTechnology.java:134) ~[TwistSpaceTechnology.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at Launch//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at Launch//cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at Launch//cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at Launch//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at Launch//cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at Launch//cpw.mods.fml.common.Loader.initializeMods(Loader.java:745) [Loader.class:?]
	at Launch//cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at Launch//cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
	at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [lt.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16:00:04] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: Class galaxyspace.core.register.GSItems does not have member field 'net.minecraft.item.Item DysonSwarmItems'
	at Launch//cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:?]
	at Launch//cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:860) [Loader.class:?]
	at Launch//cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273) [FMLCommonHandler.class:?]
	at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:256) [lt.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchFieldError: Class galaxyspace.core.register.GSItems does not have member field 'net.minecraft.item.Item DysonSwarmItems'
	at Launch//com.Nxer.TwistSpaceTechnology.recipe.machineRecipe.GTCMMachineRecipePool.loadRecipes(GTCMMachineRecipePool.java:2287) ~[GTCMMachineRecipePool.class:?]
	at Launch//com.Nxer.TwistSpaceTechnology.loader.RecipeLoader.loadRecipes(RecipeLoader.java:77) ~[RecipeLoader.class:?]
	at Launch//com.Nxer.TwistSpaceTechnology.TwistSpaceTechnology.completeInit(TwistSpaceTechnology.java:134) ~[TwistSpaceTechnology.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at Launch//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at Launch//cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at Launch//cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at Launch//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at Launch//com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at Launch//cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at Launch//cpw.mods.fml.common.Loader.initializeMods(Loader.java:745) ~[Loader.class:?]
	at Launch//cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at Launch//cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:?]
	at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) ~[lt.class:?]
	... 2 more
</code></pre> </details>

**Comment by PinkYuDeer** [comment]
同时也更新了GS。

**Comment by Nxer** [comment]
等待下两次更新吧，下次更新会继续修复一些bug，较严重bug修复完成后会升级版本适配到2.7.2

**Comment by PinkYuDeer** [comment]
好的好的 赞美N佬 目前服务器停留在780一切正常，等待更新w

**Comment by PinkYuDeer** [comment]
807依旧起不起来QAQ
